### PR TITLE
Citation Update

### PR DESCRIPTION
**Pull request by feathern**
This updates the documentation to include the appropriate citation for Rayleigh 1.0.

### CODE REVIEW

**Comment by tukss** [comment]
Looks good to me.

**Review by tukss — APPROVED** [review]

**Review by orvedahl — APPROVED** [review]
Looks good, thanks Nick.

**Review by illorenzo7 — APPROVED** [review]
Looks good! Thanks!

**Review by cianwilson — APPROVED** [review]
Thanks @feathern !

**Review by gassmoeller — APPROVED** [review]
Looks like everyone agrees :-)
Ready to merge

**Pull request merged**
