### PR TITLE
Remove cmake build system

### PR DESCRIPTION
**Pull request by gassmoeller**
The cmake build system is not used, not documented, and out of date. Because no one is interested in maintaining it we should remove it for now. If it is needed again in the future it can be recovered from the git history.

### CODE REVIEW

**Review by orvedahl — APPROVED** [review]
This looks good to me, thanks Rene.

**Comment by bangerth** [comment]
What a shame :-)

Related to #60.

**Comment by gassmoeller** [comment]
I agree, but in the interested of not keeping broken things in the repo it seemed the best solution.

**Comment by bangerth** [comment]
Yes, absolutely!

**Pull request merged**
