### PR TITLE
Update online documentation for conda environment

### PR DESCRIPTION
**Pull request by gassmoeller**
Simplify the online documentation for the development environment using the environment files. Also add a basemap package needed for the some postprocessing examples (https://rayleigh-documentation.readthedocs.io/en/latest/post_processing/Diagnostic_Plotting.html#II.-Configuring-Your-Python-Environment).

### CODE REVIEW

**Comment by tukss** [comment]
The new instructions work for me on a Linux system. Someone else should test the macOS instructions.

Is there are reason why we give the macOS environment the name `radev_mac`? I don't think you can install it at the same time as the Linux environment anyway. The different names might lead to confusion.

**Comment by feathern** [comment]
Could we remove the basemap dependency?    We're going to move to a different shell-slice plotting library that I wrote and which we can manipulate/modify as needed.   It's part of Lydia Korre's shell-slice commit.

**Comment by gassmoeller** [comment]
@tukss: Good catch, that was a leftover from @ksoderlu and my testing in #296. I unified the environment names. I also removed the basemap dependency, the reason we added it was that: https://rayleigh-documentation.readthedocs.io/en/latest/post_processing/Diagnostic_Plotting.html#II.-Configuring-Your-Python-Environment says we need it at the moment.

**Review by tukss — APPROVED** [review]
Looks good to me now. I think removing basemap is OK, as we have instructions how to install it later at the right point in the docs.

**Pull request merged**
