### PR TITLE
Fix formula for computing l_max from n_theta

### PR DESCRIPTION
**Pull request by orvedahl**
The number of spectral modes and the number of physical grid points are related as: n_theta = 3 * n_l / 2, where n_l = l_max + 1. This means: l_max = (2 * n_theta / 3 ) - 1.

Previously, if the user provided n_theta, then Rayleigh would compute l_max = (2*n_theta - 1) / 3, which is incorrect. This PR fixes the formula.

### CODE REVIEW

**Comment by orvedahl** [comment]
This should not be merged until I figure out why the CI tests are failing.

**Comment by orvedahl** [comment]
This should be good to go now. Note, I did have to update the benchmark results (numbers changed in the last few digits).

**Comment by feathern** [comment]
Hi Ryan,
Looks good. Before I merge, I want to double check that you ran the full benchmark and that the results look correct?  Having to change a digit or two in the partial benchmark check, used for the CI, makes complete sense given that the lmax has changed by 1.  Just want to verify that a full benchmark has passed too (can't see why it wouldn't).
-Nick

**Comment by orvedahl** [comment]
Yes, I ran a full benchmark and the results were as expected.

**Pull request merged**
