### PR TITLE
Add photo gallery to documentation

### PR DESCRIPTION
**Pull request by BrandonJLazard**
Added a photo gallery subsection to the "Research Enabled by Rayleigh" section of Rayleigh's documentation

### CODE REVIEW

**Comment by BrandonJLazard** [comment]
Keren gave permission to use their figure in the image gallery. Waiting on permission from Ryan and Bice

**Comment by orvedahl** [comment]
Please do use my figures, it's nice to see them getting some exercise.

**Comment by BrandonJLazard** [comment]
Everyone has given permission for their images so I believe this is ready to merge.

**Review by feathern — APPROVED** [review]
Looks good.  I'm going to approve, though I do think we should add a small description and a paper title for each image (in addition to the caption and reference that are already there).
Thanks!

**Pull request merged**
