### PR TITLE
Add TACC docker image

### PR DESCRIPTION
**Pull request by gassmoeller**
This is a preliminary PR that can create a docker image that runs on TACC Stampede2. So far I have it  only running on a single node, and unfortunately the image is quite a bit slower. I suspect this is because I have no access to MKL inside the container. I will think about this a bit more.

### CODE REVIEW

**Comment by feathern** [comment]
Is this still WIP?

**Comment by gassmoeller** [comment]
Depends how you define WIP. It is not quite done, given the limitations and the fact that the code is not really clean, but I am also not actively working on it at the moment. I hope to come back to it early next year after AGU though. If you want we can close the PR for now and I reopen once I have a better version, but we can also leave it open as a reminder. Either way is fine with me.

**Comment by feathern** [comment]
OK -- just checking.  We can leave it open.

**Comment by gassmoeller** [comment]
This is in theory ready, but I cannot check right now, because the cluster is closed for scaling tests. Will report back later.

**Comment by feathern** [comment]
Checking in again @gassmoeller .  Is this ready to merge and/or has it been superseded by any other container work in the past year?  Thanks!

**Comment by gassmoeller** [comment]
This is now ready for review. I have tested that I can build the containers and run them on Stampede3 and Frontera.

**Review by feathern — APPROVED** [review]
This looks good.  Approved.

**Pull request merged**
