### PR TITLE
Fix errors in Restore_Reference_Defaults() subroutine

### PR DESCRIPTION
**Pull request by illorenzo7**
The Restore_Reference_Defaults() routine of PDE_Coefficients was a bit out of date. Some variables were not restored to their proper values, or at all. Not all the allocatable arrays were deallocated. This pull request should fix these errors. It incorporates the code cleanup from my other pull request (#426 ).

### CODE REVIEW

**Comment by illorenzo7** [comment]
Hmmm....these pull requests are now failing after merging @feathern's custom reference tests. Fortunately, this one (which only modifies the "Restore_Reference_Defaults()" routine) is also failing, which means there must be a problem with my fix to the restore defaults---probably specifically related to the custom reference stuff. Let me look into this. Hopefully it's just an issue with "Restore_Reference_Defaults()" and an easy fix.

**Comment by feathern** [comment]
Looks like your fix passed the check.  I'm cooking dinner right now, but I'll review this in the morning and we can go from there.  And yes, the restore_reference_defaults was way out of date.  A conversation for our monthly meeting I think (others are out of date too).

**Comment by illorenzo7** [comment]
Yes, it seems like I can't reference the custom reference stuff in the restore defaults routine yet. I'm not entirely sure what's going on, or whether the problem is on this end, or the new custom tests' end. Anyway, I will try rebasing the other pull requests of this (slightly "incomplete" Restore_Reference_Defaults() routine--should be a relatively easy thing to fix later, and I'd like to get that other stuff (which feels more critical, since there were some bugs) rolling. Hopefully this was the whole issue, and the other pull requests pass the checks after rebasing. We'll see!

**Comment by feathern** [comment]
Two things:
1)  I can merge this once the commented lines are deleted rather than commented.  I'm referring to the lines you had to fix to make this work.
2)  The issue here was that restore_reference_defaults is called as part of the benchmarking initialization.  We wanted to ensure that benchmarking mode could be used as a way of testing the custom reference state framework.  When benchmarking mode is used alongside a custom reference state, a few variables (like ref_type) are saved and restored following the call to restore_reference_defaults.  The lines you commented out were effectively undoing whatever had previously been read in from main_input describing the custom reference state, and so the tests were rightfully failing.

It's worth noting that restore_reference_defaults is now only used for benchmarking and doesn't necessarily need to actually restore all of the default values as it did in the past.

**Comment by illorenzo7** [comment]
OK, I will go ahead and delete these. I'm fairly unfamiliar with these routines. Basically, I went off the lines

1145         ! Restore all variables in this module to their default state.
1146         ! Deallocates all allocatable module variables.

Anyway, it sounds like we'll be discussing these routines in general, so as long as you think it's doing what it's supposed to now, that's fine.

**Comment by illorenzo7** [comment]
Just fixed this but it triggered another test (I submitted commit directly from Github).

**Review by feathern — APPROVED** [review]
OK, looks good. Merging now.

**Pull request merged**
