### PR TITLE
Added finite-difference support to the log_deriv subroutine.

### PR DESCRIPTION
**Pull request by feathern**
This PR should fix the finite-difference part of issue #570 reported by @rpvin . Please try this out when you get a chance to see if initialization now works properly for custom reference states with FD turned on.

### CODE REVIEW

**Comment by tukss** [comment]
There was a missing if guard around the deallocate. I've pushed that directly to your branch.

**Comment by feathern** [comment]
Good catch.  I just moved the deallocate statement into the main Chebyshev "if" block to save a couple of lines of code + keep related things together.

**Comment by tukss** [comment]
That looks good. I'm just running some tests here and will approve this later today if all goes well.

**Comment by tukss** [comment]
It seems to work fine with gfortran but I'm getting a floating-point overflow after the first time step with the Intel compiler (the new LLVM based one). I'm investigating where this comes from.

**Comment by tukss** [comment]
OK. That seems to have been some bad interaction of Cray libsci as the LAPACK provider and the `ifx` compiler. Switching to MKL instead fixes the problem.

**Review by tukss — APPROVED** [review]
Works in my test cases.

**Comment by feathern** [comment]
Great -- thanks for checking that.

**Pull request merged**
