### PR TITLE
Shell slice and spectra consistency

### PR DESCRIPTION
**Pull request by illorenzo7**
Makes doc string (regarding indices) compatible with new doc strings for Point_Probes and Meridional_Slices. Also gives Shell_Slices, Shell_Spectra, SPH_Modes, and Power_Spectrum the alternate property

rad_inds (for compatability with Point_Probes)

identical to 

inds (for backwards compatability). 

There used to only be the property inds.

### CODE REVIEW

**Comment by illorenzo7** [comment]
Note: I tested this for Power_Spectrum, Shell_Spectra, and Shell_Slices, but I don't have any sample SPH_Modes (and I am also unfamiliar with that output). If someone wants to test on SPH_Modes that would be great!

**Comment by feathern** [comment]
Hi Loren,
This looks good to me.  Just to be sure, though, can you confirm that you read in sample files for those classes whose init routines you modified (not worried about the docstrings).
-Nick

**Comment by illorenzo7** [comment]
I haven't checked the SPH_Modes and it looks like there are multiple ways to initialize the Power_Spectrum. I will check on this now and leave another comment, hopefully shortly.

**Comment by feathern** [comment]
OK thanks.  I suspect it's fine, but just to be safe it's good to run through a few read-ins.

**Comment by illorenzo7** [comment]
OK, I just checked the SPH_Modes and other (blank and power_file) options to initialize Power_Spectrum. It seems good on my end!

**Review by feathern — APPROVED** [review]
Great.  Approved.

**Pull request merged**
